### PR TITLE
upgraded template + marawa

### PR DESCRIPTION
**Pull request by nvdk**
the new template was incompatible with the version of marawa we used

### CODE REVIEW

**Comment by nvdk** [comment]
depends on https://github.com/mu-semtech/mu-javascript-template/pull/27 being released

**Comment by nvdk** [comment]
Looks to be working correctly now :tada:

**Review by lagartoverde — APPROVED** [review]
Looks good to me 👍.
The only question would be why we change from semtech/mu-javascript-template to nvdk/mu-javascript-template? but I guess that's due to internal reasons

**Comment by nvdk** [comment]
> Looks good to me +1.
> The only question would be why we change from semtech/mu-javascript-template to nvdk/mu-javascript-template? but I guess that's due to internal reasons

we can switch back when the PRs I've mentioned have been merged.

**Comment by lagartoverde** [comment]
Ook, then all perfect for me :)

**Pull request merged**
