### PR TITLE
created endpoint for generating final notulen preview with public behandelings

### PR DESCRIPTION
**Pull request by lagartoverde**

### CODE REVIEW

**Comment by lagartoverde** [comment]
Related to https://github.com/lblod/frontend-gelinkt-notuleren/pull/249

**Review by benjay10 — APPROVED** [review]
Not familiar with this service yet, but as the frontend seems to do what it needs to do, these changes seems reasonable at first glance.

**Comment by nvdk** [comment]
I would very much like it if the api can adhere to json:api standards

**Comment by lagartoverde** [comment]
Now also related to https://github.com/lblod/app-gelinkt-notuleren/pull/81

**Pull request merged**
